### ISSUE TITLE
installation not possible in QGIS3.10.7 - error message

### ISSUE THREAD

**Issue by lucky2d** [GeODinTeam/GeODinQGIS#2]
Error message:

--------------------------------------------------------------------
Konnte Erweiterung 'GeODinQGIS' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Deutschmann/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeODinQGIS\__init__.py", line 34, in classFactory
    from .GeODinQGIS import GeODinQGIS
  File "C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GeODinQGIS\GeODinQGIS.py", line 195
    except Exception,e :
                    ^
SyntaxError: invalid syntax
------------------------------------------------------------------------------

**Comment by ebertjo** [comment]
GeODinQGIS Plugin version 3.0.2335.1 is now available.
Spin-off for GeODin 9.5 (64 bit) requires QGIS 3 (64 bit)
